version: "2.1"
services:
  # This Postgres DB matches the Postgres version used in WeOS' RDS
  rds:
    image: postgres:10.7
    container_name: weos_crm_rds
    environment: &rdsConfig
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - ACCOUNT_NAME=$ACCOUNT_NAME
      - ACCOUNT_ID=$ACCOUNT_ID
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5432:5432

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  redis:
    image: redis:alpine

  query:
    build: ./apps/query
    hostname: weos_crm_query
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - ACCOUNT_NAME=$ACCOUNT_NAME
      - ACCOUNT_ID=$ACCOUNT_ID
      - ELASTICSEARCH_ENDPOINT=http://es01:9200
      - ELASTICSEARCH_URL=http://es01:9200
      - LOG_LEVEL=debug
    depends_on:
      rds:
        condition: service_healthy
    
  api-gateway:
    build: ./apps/api-gateway
    volumes:
      - ./apps/api-gateway/logs:/var/logs
    environment:
      - ACCOUNT_ID=$ACCOUNT_ID
      - ACCOUNT_NAME=$ACCOUNT_NAME
    ports:
      - 8100:80
    depends_on:
      client-app:
        condition: service_started
      query:
        condition: service_started

  client-app:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: app
    hostname: weos_crm_client_app
    environment:
      - LOG_LEVEL=debug
      - BASE_URL=$BASE_URL
      - GRAPHQL_URL=$GRAPHQL_URL
      - ACCOUNT_ID=$ACCOUNT_ID
      - APPLICATION_TITLE=WeOS
      - APPLICATION_ID=$APPLICATION_ID
      - ACCOUNT_NAME=$ACCOUNT_NAME
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - LOGIN_URL=$LOGIN_URL
      - SESSION_KEY=$SESSION_KEY
      - SECRET=$SECRET

    volumes:
      - ./apps/web/weplugin/templates:/app/templates
      - ./apps/web/api.yaml:/app/api.yaml
      - ./apps/web/weos-crm:/app/weos-crm
    depends_on:
      rds:
        condition: service_healthy

  account-app:
    build:
      context: ./apps/account
      dockerfile: Dockerfile
      target: app
    hostname: weos_crm_account_app
    environment:
      - LOG_LEVEL=debug
      - BASE_URL=$BASE_URL
      - GRAPHQL_URL=$GRAPHQL_URL
      - ACCOUNT_ID=$ACCOUNT_ID
      - APPLICATION_TITLE=WeOS
      - APPLICATION_ID=$APPLICATION_ID
      - ACCOUNT_NAME=$ACCOUNT_NAME
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - EMAIL_URL=$EMAIL_URL
      - SESSION_KEY=$SESSION_KEY
      - ACCOUNT_URL=$ACCOUNT_URL


    volumes:
      - ./apps/account/weplugin/templates:/app/templates
      - ./apps/account/api.yaml:/app/api.yaml
      - ./apps/account/weos-crm:/app/weos-crm
    depends_on:
      rds:
        condition: service_healthy
